/*insert data to datbase*/

insert into [dbo].customers([Id],[FirstName],[Email],[region])
values
(1,'hossein','h@ff.com','kish'),
(2,'ali','a@ff.com','shiraz'),
(3,'hamed','m@ff.com','esfahn');
go


insert into products (ProductName, ProductPrice, Stock) values ('alcatel OT 320', 1031.0, 1);
insert into products (ProductName, ProductPrice, Stock) values ('Nokia 7270', 972.81, 2);
insert into products (ProductName, ProductPrice, Stock) values ('alcatel 2012', 361.84, 3);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung R520 Trill', 235.61, 4);
insert into products (ProductName, ProductPrice, Stock) values ('Orange Rio', 531.55, 5);
insert into products (ProductName, ProductPrice, Stock) values ('Sagem myMobileTV 2', 1829.97, 6);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola Moto G 4G (2nd gen)', 1328.28, 7);
insert into products (ProductName, ProductPrice, Stock) values ('Huawei T201', 1274.09, 8);
insert into products (ProductName, ProductPrice, Stock) values ('Sony Ericsson Xperia Neo', 504.29, 9);
insert into products (ProductName, ProductPrice, Stock) values ('LG G Pad III 10.1 FHD', 1111.91, 10);
insert into products (ProductName, ProductPrice, Stock) values ('HTC Ozone', 612.54, 11);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola W7 Active Edition', 1618.0, 12);
insert into products (ProductName, ProductPrice, Stock) values ('Benefon Esc!', 1920.27, 13);
insert into products (ProductName, ProductPrice, Stock) values ('Prestigio MultiPad Note 8.0 3G', 658.85, 14);
insert into products (ProductName, ProductPrice, Stock) values ('Celkon C66+', 222.7, 15);
insert into products (ProductName, ProductPrice, Stock) values ('AT&T Quickfire', 1769.99, 16);
insert into products (ProductName, ProductPrice, Stock) values ('Gionee F103 Pro', 1824.95, 17);
insert into products (ProductName, ProductPrice, Stock) values ('NEC c616v', 1744.22, 18);
insert into products (ProductName, ProductPrice, Stock) values ('Sagem my234x', 962.75, 19);
insert into products (ProductName, ProductPrice, Stock) values ('vivo Y70s', 257.3, 20);
insert into products (ProductName, ProductPrice, Stock) values ('vivo V15 Pro', 1819.67, 21);
insert into products (ProductName, ProductPrice, Stock) values ('Microsoft Lumia 640 XL', 1181.78, 22);
insert into products (ProductName, ProductPrice, Stock) values ('Ulefone Armor 7', 1593.85, 23);
insert into products (ProductName, ProductPrice, Stock) values ('LG GW880', 1067.07, 24);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola EX128', 726.71, 25);
insert into products (ProductName, ProductPrice, Stock) values ('Yezz Andy 3G 3.5 YZ1110', 1365.7, 26);
insert into products (ProductName, ProductPrice, Stock) values ('Energizer Ultimate U570S', 1808.17, 27);
insert into products (ProductName, ProductPrice, Stock) values ('Huawei MediaPad M5 10', 1760.64, 28);
insert into products (ProductName, ProductPrice, Stock) values ('Amoi A9B', 1969.92, 29);
insert into products (ProductName, ProductPrice, Stock) values ('Sony Ericsson Jalou', 462.13, 30);
insert into products (ProductName, ProductPrice, Stock) values ('Karbonn K102+ Flair', 1041.52, 31);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung Galaxy Grand 2', 344.97, 32);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola V600', 258.19, 33);
insert into products (ProductName, ProductPrice, Stock) values ('Xiaomi Mi Mix 3 5G', 901.98, 34);
insert into products (ProductName, ProductPrice, Stock) values ('Nokia 105 Dual SIM (2015)', 371.84, 35);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung Galaxy M11', 100.17, 36);
insert into products (ProductName, ProductPrice, Stock) values ('alcatel OT-S621', 386.01, 37);
insert into products (ProductName, ProductPrice, Stock) values ('Sony Ericsson Xperia X1', 1360.94, 38);
insert into products (ProductName, ProductPrice, Stock) values ('Huawei Ascend G615', 465.29, 39);
insert into products (ProductName, ProductPrice, Stock) values ('Spice M 4580', 900.01, 40);
insert into products (ProductName, ProductPrice, Stock) values ('Celkon A21', 417.32, 41);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung Galaxy M51', 143.7, 42);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola EX210', 1344.41, 43);
insert into products (ProductName, ProductPrice, Stock) values ('Oppo F7 Youth', 891.13, 44);
insert into products (ProductName, ProductPrice, Stock) values ('Archos 50b Helium 4G', 1046.67, 45);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola Accompli 008', 1530.48, 46);
insert into products (ProductName, ProductPrice, Stock) values ('Lava Iris X5', 1339.74, 47);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung E730', 511.99, 48);
insert into products (ProductName, ProductPrice, Stock) values ('BLU Life One XL', 1126.17, 49);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung E1080T', 398.76, 50);
insert into products (ProductName, ProductPrice, Stock) values ('Panasonic Eluga Note', 1854.24, 51);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola WX180', 439.86, 52);
insert into products (ProductName, ProductPrice, Stock) values ('Spice Mi-530 Stellar Pinnacle', 1023.58, 53);
insert into products (ProductName, ProductPrice, Stock) values ('Siemens Xelibri 6', 1798.32, 54);
insert into products (ProductName, ProductPrice, Stock) values ('Realme GT 5G', 1742.45, 55);
insert into products (ProductName, ProductPrice, Stock) values ('Nokia 5132 XpressMusic', 1611.75, 56);
insert into products (ProductName, ProductPrice, Stock) values ('Sagem MC 959', 356.59, 57);
insert into products (ProductName, ProductPrice, Stock) values ('ZTE Blade 20', 1024.74, 58);
insert into products (ProductName, ProductPrice, Stock) values ('ZTE N910', 973.04, 59);
insert into products (ProductName, ProductPrice, Stock) values ('Micromax Bharat 5 Infinity', 1526.85, 60);
insert into products (ProductName, ProductPrice, Stock) values ('Celkon C44', 1202.68, 61);
insert into products (ProductName, ProductPrice, Stock) values ('Toshiba TS10', 193.47, 62);
insert into products (ProductName, ProductPrice, Stock) values ('Nokia 6700 slide', 1726.9, 63);
insert into products (ProductName, ProductPrice, Stock) values ('BLU Energy X Plus', 1017.71, 64);
insert into products (ProductName, ProductPrice, Stock) values ('Sony Ericsson W830', 1702.28, 65);
insert into products (ProductName, ProductPrice, Stock) values ('Sony Ericsson W800', 613.54, 66);
insert into products (ProductName, ProductPrice, Stock) values ('LG KP270', 991.64, 67);
insert into products (ProductName, ProductPrice, Stock) values ('LG Optimus L4 II Dual E445', 415.45, 68);
insert into products (ProductName, ProductPrice, Stock) values ('Micromax A85', 1440.6, 69);
insert into products (ProductName, ProductPrice, Stock) values ('BenQ-Siemens EF81', 498.63, 70);
insert into products (ProductName, ProductPrice, Stock) values ('Oppo R2001 Yoyo', 1407.01, 71);
insert into products (ProductName, ProductPrice, Stock) values ('BLU G50', 576.03, 72);
insert into products (ProductName, ProductPrice, Stock) values ('Philips 193', 1867.01, 73);
insert into products (ProductName, ProductPrice, Stock) values ('O2 XDA phone', 1022.54, 74);
insert into products (ProductName, ProductPrice, Stock) values ('LG Optimus Black P970', 486.59, 75);
insert into products (ProductName, ProductPrice, Stock) values ('Celkon C349i', 1866.71, 76);
insert into products (ProductName, ProductPrice, Stock) values ('BlackBerry Z10', 1154.41, 77);
insert into products (ProductName, ProductPrice, Stock) values ('ZTE N880E', 1074.48, 78);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung B520', 434.23, 79);
insert into products (ProductName, ProductPrice, Stock) values ('Pantech PG-3600V', 1279.67, 80);
insert into products (ProductName, ProductPrice, Stock) values ('Huawei Ascend Mate', 382.81, 81);
insert into products (ProductName, ProductPrice, Stock) values ('Ulefone Armor 9', 1669.51, 82);
insert into products (ProductName, ProductPrice, Stock) values ('Pantech Discover', 1508.53, 83);
insert into products (ProductName, ProductPrice, Stock) values ('alcatel Miss Sixty', 1608.13, 84);
insert into products (ProductName, ProductPrice, Stock) values ('Micromax A52', 1949.19, 85);
insert into products (ProductName, ProductPrice, Stock) values ('Acer Iconia Tab 7 A1-713', 512.93, 86);
insert into products (ProductName, ProductPrice, Stock) values ('Yezz Andy 3G 4.0 YZ1120', 1336.3, 87);
insert into products (ProductName, ProductPrice, Stock) values ('Google Pixel 4', 504.52, 88);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola V400p', 980.82, 89);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung Galaxy J4 Core', 464.84, 90);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung Galaxy Rugby Pro I547', 1233.18, 91);
insert into products (ProductName, ProductPrice, Stock) values ('Energizer Ultimate U710S', 952.5, 92);
insert into products (ProductName, ProductPrice, Stock) values ('Nokia 6630', 1926.31, 93);
insert into products (ProductName, ProductPrice, Stock) values ('HTC Desire X', 185.74, 94);
insert into products (ProductName, ProductPrice, Stock) values ('Motorola Moto G9 (India)', 229.16, 95);
insert into products (ProductName, ProductPrice, Stock) values ('Samsung N620', 1283.49, 96);
insert into products (ProductName, ProductPrice, Stock) values ('ZTE Avid 4G', 735.35, 97);
insert into products (ProductName, ProductPrice, Stock) values ('Acer Liquid Zest Plus', 465.18, 98);
insert into products (ProductName, ProductPrice, Stock) values ('Amazon Kindle Fire HDX', 1522.58, 99);
insert into products (ProductName, ProductPrice, Stock) values ('Karbonn A5', 1571.15, 100);

insert into categories (CategoryName) values ('Panasonic');
insert into categories (CategoryName) values ('Sharp');
insert into categories (CategoryName) values ('Lenovo');
insert into categories (CategoryName) values ('LG');
insert into categories (CategoryName) values ('Sagem');
insert into categories (CategoryName) values ('Apple');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('Honor');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Realme');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('HTC');
insert into categories (CategoryName) values ('XOLO');
insert into categories (CategoryName) values ('LG');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Innostream');
insert into categories (CategoryName) values ('Bird');
insert into categories (CategoryName) values ('Lava');
insert into categories (CategoryName) values ('Panasonic');
insert into categories (CategoryName) values ('LG');
insert into categories (CategoryName) values ('Wiko');
insert into categories (CategoryName) values ('alcatel');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('Lenovo');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('Huawei');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('alcatel');
insert into categories (CategoryName) values ('Icemobile');
insert into categories (CategoryName) values ('O2');
insert into categories (CategoryName) values ('alcatel');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('BLU');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('Philips');
insert into categories (CategoryName) values ('Energizer');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Huawei');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('Archos');
insert into categories (CategoryName) values ('Gionee');
insert into categories (CategoryName) values ('Lenovo');
insert into categories (CategoryName) values ('Sony');
insert into categories (CategoryName) values ('Microsoft');
insert into categories (CategoryName) values ('ZTE');
insert into categories (CategoryName) values ('Asus');
insert into categories (CategoryName) values ('QMobile');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('Micromax');
insert into categories (CategoryName) values ('ZTE');
insert into categories (CategoryName) values ('Allview');
insert into categories (CategoryName) values ('Acer');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('Motorola');
insert into categories (CategoryName) values ('BenQ-Siemens');
insert into categories (CategoryName) values ('Huawei');
insert into categories (CategoryName) values ('Sharp');
insert into categories (CategoryName) values ('Xiaomi');
insert into categories (CategoryName) values ('alcatel');
insert into categories (CategoryName) values ('Lenovo');
insert into categories (CategoryName) values ('Panasonic');
insert into categories (CategoryName) values ('LG');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('HTC');
insert into categories (CategoryName) values ('LG');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('HTC');
insert into categories (CategoryName) values ('HTC');
insert into categories (CategoryName) values ('Sharp');
insert into categories (CategoryName) values ('Mitsubishi');
insert into categories (CategoryName) values ('Neonode');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('T-Mobile');
insert into categories (CategoryName) values ('Nokia');
insert into categories (CategoryName) values ('Sony');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Xiaomi');
insert into categories (CategoryName) values ('vivo');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Samsung');
insert into categories (CategoryName) values ('Philips');
insert into categories (CategoryName) values ('ZTE');
insert into categories (CategoryName) values ('BlackBerry');
insert into categories (CategoryName) values ('Huawei');
insert into categories (CategoryName) values ('Plum');
insert into categories (CategoryName) values ('Panasonic');
insert into categories (CategoryName) values ('Eten');
insert into categories (CategoryName) values ('Kyocera');
insert into categories (CategoryName) values ('Plum');
insert into categories (CategoryName) values ('Philips');

insert into  productAndCategory (ProductId, CategoryId) values (178, 29);
insert into  productAndCategory (ProductId, CategoryId) values (121, 50);
insert into  productAndCategory (ProductId, CategoryId) values (107, 47);
insert into  productAndCategory (ProductId, CategoryId) values (188, 44);
insert into  productAndCategory (ProductId, CategoryId) values (143, 22);
insert into  productAndCategory (ProductId, CategoryId) values (186, 29);
insert into  productAndCategory (ProductId, CategoryId) values (190, 43);
insert into  productAndCategory (ProductId, CategoryId) values (131, 27);
insert into  productAndCategory (ProductId, CategoryId) values (199, 44);
insert into  productAndCategory (ProductId, CategoryId) values (118, 17);
insert into  productAndCategory (ProductId, CategoryId) values (156, 5);
insert into  productAndCategory (ProductId, CategoryId) values (168, 8);
insert into  productAndCategory (ProductId, CategoryId) values (134, 38);
insert into  productAndCategory (ProductId, CategoryId) values (189, 5);
insert into  productAndCategory (ProductId, CategoryId) values (136, 25);
insert into  productAndCategory (ProductId, CategoryId) values (156, 28);
insert into  productAndCategory (ProductId, CategoryId) values (171, 16);
insert into  productAndCategory (ProductId, CategoryId) values (166, 6);
insert into  productAndCategory (ProductId, CategoryId) values (197, 18);
insert into  productAndCategory (ProductId, CategoryId) values (141, 34);
insert into  productAndCategory (ProductId, CategoryId) values (108, 27);
insert into  productAndCategory (ProductId, CategoryId) values (112, 3);
insert into  productAndCategory (ProductId, CategoryId) values (187, 50);
insert into  productAndCategory (ProductId, CategoryId) values (200, 14);
insert into  productAndCategory (ProductId, CategoryId) values (143, 42);
insert into  productAndCategory (ProductId, CategoryId) values (182, 20);
insert into  productAndCategory (ProductId, CategoryId) values (164, 5);
insert into  productAndCategory (ProductId, CategoryId) values (111, 20);
insert into  productAndCategory (ProductId, CategoryId) values (120, 37);
insert into  productAndCategory (ProductId, CategoryId) values (129, 34);
insert into  productAndCategory (ProductId, CategoryId) values (188, 44);
insert into  productAndCategory (ProductId, CategoryId) values (190, 17);
insert into  productAndCategory (ProductId, CategoryId) values (113, 50);
insert into  productAndCategory (ProductId, CategoryId) values (183, 27);
insert into  productAndCategory (ProductId, CategoryId) values (201, 43);
insert into  productAndCategory (ProductId, CategoryId) values (187, 44);
insert into  productAndCategory (ProductId, CategoryId) values (160, 34);
insert into  productAndCategory (ProductId, CategoryId) values (133, 35);
insert into  productAndCategory (ProductId, CategoryId) values (111, 35);
insert into  productAndCategory (ProductId, CategoryId) values (164, 15);
insert into  productAndCategory (ProductId, CategoryId) values (167, 33);
insert into  productAndCategory (ProductId, CategoryId) values (196, 39);
insert into  productAndCategory (ProductId, CategoryId) values (158, 2);
insert into  productAndCategory (ProductId, CategoryId) values (191, 15);
insert into  productAndCategory (ProductId, CategoryId) values (152, 2);
insert into  productAndCategory (ProductId, CategoryId) values (156, 43);
insert into  productAndCategory (ProductId, CategoryId) values (187, 6);
insert into  productAndCategory (ProductId, CategoryId) values (116, 15);
insert into  productAndCategory (ProductId, CategoryId) values (170, 37);
insert into  productAndCategory (ProductId, CategoryId) values (184, 24);
insert into  productAndCategory (ProductId, CategoryId) values (138, 48);
insert into  productAndCategory (ProductId, CategoryId) values (189, 47);
insert into  productAndCategory (ProductId, CategoryId) values (157, 28);
insert into  productAndCategory (ProductId, CategoryId) values (137, 2);
insert into  productAndCategory (ProductId, CategoryId) values (175, 50);
insert into  productAndCategory (ProductId, CategoryId) values (127, 11);
insert into  productAndCategory (ProductId, CategoryId) values (173, 1);
insert into  productAndCategory (ProductId, CategoryId) values (136, 1);
insert into  productAndCategory (ProductId, CategoryId) values (163, 42);
insert into  productAndCategory (ProductId, CategoryId) values (196, 20);
insert into  productAndCategory (ProductId, CategoryId) values (107, 6);
insert into  productAndCategory (ProductId, CategoryId) values (123, 34);
insert into  productAndCategory (ProductId, CategoryId) values (128, 29);
insert into  productAndCategory (ProductId, CategoryId) values (135, 5);
insert into  productAndCategory (ProductId, CategoryId) values (164, 34);
insert into  productAndCategory (ProductId, CategoryId) values (159, 11);
insert into  productAndCategory (ProductId, CategoryId) values (122, 36);
insert into  productAndCategory (ProductId, CategoryId) values (104, 21);
insert into  productAndCategory (ProductId, CategoryId) values (127, 36);
insert into  productAndCategory (ProductId, CategoryId) values (177, 17);
insert into  productAndCategory (ProductId, CategoryId) values (186, 38);
insert into  productAndCategory (ProductId, CategoryId) values (189, 29);
insert into  productAndCategory (ProductId, CategoryId) values (114, 5);
insert into  productAndCategory (ProductId, CategoryId) values (123, 2);
insert into  productAndCategory (ProductId, CategoryId) values (195, 36);
insert into  productAndCategory (ProductId, CategoryId) values (148, 40);
insert into  productAndCategory (ProductId, CategoryId) values (118, 23);
insert into  productAndCategory (ProductId, CategoryId) values (191, 2);
insert into  productAndCategory (ProductId, CategoryId) values (163, 11);
insert into  productAndCategory (ProductId, CategoryId) values (120, 8);
insert into  productAndCategory (ProductId, CategoryId) values (126, 27);
insert into  productAndCategory (ProductId, CategoryId) values (171, 43);
insert into  productAndCategory (ProductId, CategoryId) values (151, 4);
insert into  productAndCategory (ProductId, CategoryId) values (169, 20);
insert into  productAndCategory (ProductId, CategoryId) values (178, 21);
insert into  productAndCategory (ProductId, CategoryId) values (188, 21);
insert into  productAndCategory (ProductId, CategoryId) values (132, 44);
insert into  productAndCategory (ProductId, CategoryId) values (200, 3);
insert into  productAndCategory (ProductId, CategoryId) values (125, 13);
insert into  productAndCategory (ProductId, CategoryId) values (128, 15);
insert into  productAndCategory (ProductId, CategoryId) values (167, 27);
insert into  productAndCategory (ProductId, CategoryId) values (151, 18);
insert into  productAndCategory (ProductId, CategoryId) values (107, 5);
insert into  productAndCategory (ProductId, CategoryId) values (178, 6);
insert into  productAndCategory (ProductId, CategoryId) values (159, 20);
insert into  productAndCategory (ProductId, CategoryId) values (192, 48);
insert into  productAndCategory (ProductId, CategoryId) values (128, 15);
insert into  productAndCategory (ProductId, CategoryId) values (172, 8);
insert into  productAndCategory (ProductId, CategoryId) values (166, 24);
insert into  productAndCategory (ProductId, CategoryId) values (168, 20);
/* 2 insert to productAndCategory table*/
insert into  productAndCategory (ProductId, CategoryId) values (114, 54);
insert into  productAndCategory (ProductId, CategoryId) values (196, 50);
insert into  productAndCategory (ProductId, CategoryId) values (143, 59);
insert into  productAndCategory (ProductId, CategoryId) values (114, 73);
insert into  productAndCategory (ProductId, CategoryId) values (116, 63);
insert into  productAndCategory (ProductId, CategoryId) values (166, 93);
insert into  productAndCategory (ProductId, CategoryId) values (141, 52);
insert into  productAndCategory (ProductId, CategoryId) values (148, 92);
insert into  productAndCategory (ProductId, CategoryId) values (128, 82);
insert into  productAndCategory (ProductId, CategoryId) values (155, 76);
insert into  productAndCategory (ProductId, CategoryId) values (107, 86);
insert into  productAndCategory (ProductId, CategoryId) values (163, 87);
insert into  productAndCategory (ProductId, CategoryId) values (141, 68);
insert into  productAndCategory (ProductId, CategoryId) values (161, 93);
insert into  productAndCategory (ProductId, CategoryId) values (190, 71);
insert into  productAndCategory (ProductId, CategoryId) values (184, 52);
insert into  productAndCategory (ProductId, CategoryId) values (153, 61);
insert into  productAndCategory (ProductId, CategoryId) values (136, 58);
insert into  productAndCategory (ProductId, CategoryId) values (186, 56);
insert into  productAndCategory (ProductId, CategoryId) values (105, 68);
insert into  productAndCategory (ProductId, CategoryId) values (105, 81);
insert into  productAndCategory (ProductId, CategoryId) values (111, 83);
insert into  productAndCategory (ProductId, CategoryId) values (117, 73);
insert into  productAndCategory (ProductId, CategoryId) values (170, 91);
insert into  productAndCategory (ProductId, CategoryId) values (172, 89);
insert into  productAndCategory (ProductId, CategoryId) values (117, 56);
insert into  productAndCategory (ProductId, CategoryId) values (117, 66);
insert into  productAndCategory (ProductId, CategoryId) values (109, 70);
insert into  productAndCategory (ProductId, CategoryId) values (159, 56);
insert into  productAndCategory (ProductId, CategoryId) values (132, 50);
insert into  productAndCategory (ProductId, CategoryId) values (172, 54);
insert into  productAndCategory (ProductId, CategoryId) values (114, 69);
insert into  productAndCategory (ProductId, CategoryId) values (143, 57);
insert into  productAndCategory (ProductId, CategoryId) values (178, 90);
insert into  productAndCategory (ProductId, CategoryId) values (158, 75);
insert into  productAndCategory (ProductId, CategoryId) values (148, 100);
insert into  productAndCategory (ProductId, CategoryId) values (181, 65);
insert into  productAndCategory (ProductId, CategoryId) values (144, 56);
insert into  productAndCategory (ProductId, CategoryId) values (133, 96);
insert into  productAndCategory (ProductId, CategoryId) values (179, 79);
insert into  productAndCategory (ProductId, CategoryId) values (198, 86);
insert into  productAndCategory (ProductId, CategoryId) values (156, 94);
insert into  productAndCategory (ProductId, CategoryId) values (183, 57);
insert into  productAndCategory (ProductId, CategoryId) values (158, 54);
insert into  productAndCategory (ProductId, CategoryId) values (151, 80);
insert into  productAndCategory (ProductId, CategoryId) values (140, 87);
insert into  productAndCategory (ProductId, CategoryId) values (109, 94);
insert into  productAndCategory (ProductId, CategoryId) values (105, 96);
insert into  productAndCategory (ProductId, CategoryId) values (125, 59);
insert into  productAndCategory (ProductId, CategoryId) values (136, 68);
insert into  productAndCategory (ProductId, CategoryId) values (165, 53);
insert into  productAndCategory (ProductId, CategoryId) values (181, 80);
insert into  productAndCategory (ProductId, CategoryId) values (195, 54);
insert into  productAndCategory (ProductId, CategoryId) values (125, 84);
insert into  productAndCategory (ProductId, CategoryId) values (196, 76);
insert into  productAndCategory (ProductId, CategoryId) values (130, 97);
insert into  productAndCategory (ProductId, CategoryId) values (183, 72);
insert into  productAndCategory (ProductId, CategoryId) values (109, 53);
insert into  productAndCategory (ProductId, CategoryId) values (126, 54);
insert into  productAndCategory (ProductId, CategoryId) values (201, 78);
insert into  productAndCategory (ProductId, CategoryId) values (124, 71);
insert into  productAndCategory (ProductId, CategoryId) values (190, 82);
insert into  productAndCategory (ProductId, CategoryId) values (185, 96);
insert into  productAndCategory (ProductId, CategoryId) values (123, 100);
insert into  productAndCategory (ProductId, CategoryId) values (195, 84);
insert into  productAndCategory (ProductId, CategoryId) values (159, 59);
insert into  productAndCategory (ProductId, CategoryId) values (166, 61);
insert into  productAndCategory (ProductId, CategoryId) values (193, 55);
insert into  productAndCategory (ProductId, CategoryId) values (106, 52);
insert into  productAndCategory (ProductId, CategoryId) values (112, 62);
insert into  productAndCategory (ProductId, CategoryId) values (141, 93);
insert into  productAndCategory (ProductId, CategoryId) values (136, 87);
insert into  productAndCategory (ProductId, CategoryId) values (162, 72);
insert into  productAndCategory (ProductId, CategoryId) values (180, 56);
insert into  productAndCategory (ProductId, CategoryId) values (187, 64);
insert into  productAndCategory (ProductId, CategoryId) values (120, 86);
insert into  productAndCategory (ProductId, CategoryId) values (177, 94);
insert into  productAndCategory (ProductId, CategoryId) values (194, 72);
insert into  productAndCategory (ProductId, CategoryId) values (124, 80);
insert into  productAndCategory (ProductId, CategoryId) values (170, 75);
insert into  productAndCategory (ProductId, CategoryId) values (157, 54);
insert into  productAndCategory (ProductId, CategoryId) values (130, 79);
insert into  productAndCategory (ProductId, CategoryId) values (106, 52);
insert into  productAndCategory (ProductId, CategoryId) values (122, 71);
insert into  productAndCategory (ProductId, CategoryId) values (133, 90);
insert into  productAndCategory (ProductId, CategoryId) values (123, 93);
insert into  productAndCategory (ProductId, CategoryId) values (164, 83);
insert into  productAndCategory (ProductId, CategoryId) values (123, 61);
insert into  productAndCategory (ProductId, CategoryId) values (165, 65);
insert into  productAndCategory (ProductId, CategoryId) values (109, 86);
insert into  productAndCategory (ProductId, CategoryId) values (134, 73);
insert into  productAndCategory (ProductId, CategoryId) values (131, 52);
insert into  productAndCategory (ProductId, CategoryId) values (127, 90);
insert into  productAndCategory (ProductId, CategoryId) values (173, 75);
insert into  productAndCategory (ProductId, CategoryId) values (140, 73);
insert into  productAndCategory (ProductId, CategoryId) values (182, 63);
insert into  productAndCategory (ProductId, CategoryId) values (149, 93);
insert into  productAndCategory (ProductId, CategoryId) values (146, 69);
insert into  productAndCategory (ProductId, CategoryId) values (128, 60);
insert into  productAndCategory (ProductId, CategoryId) values (104, 79);

select * from productAndCategory
/*order item*/
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (37, 164, 1, 1511.9);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (88, 212, 2, 2479.61);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (11, 144, 3, 2770.3);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (65, 204, 4, 2080.27);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (58, 274, 5, 2670.41);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (100, 192, 6, 2328.26);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (36, 240, 7, 1069.14);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (12, 248, 8, 1224.8);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (10, 291, 9, 1106.84);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (88, 159, 10, 2015.88);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (19, 165, 11, 1628.65);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (69, 256, 12, 1989.93);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (51, 161, 13, 2794.56);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (59, 185, 14, 1725.78);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (63, 246, 15, 1661.61);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (43, 189, 16, 1595.34);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (98, 106, 17, 2406.67);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (69, 109, 18, 2246.42);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (64, 289, 19, 1590.05);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (48, 114, 20, 2344.03);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (95, 135, 21, 1839.02);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (59, 275, 22, 1800.48);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (42, 135, 23, 2983.48);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (13, 277, 24, 1720.96);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (63, 103, 25, 1206.3);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (22, 251, 26, 2312.05);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (84, 152, 27, 1906.45);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (51, 103, 28, 2935.62);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (60, 281, 29, 2989.86);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (77, 293, 30, 1826.36);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (94, 218, 31, 1601.02);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (72, 112, 32, 1985.39);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (65, 197, 33, 1779.42);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (87, 245, 34, 2247.97);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (30, 135, 35, 1910.46);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (43, 267, 36, 1179.11);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (3, 260, 37, 1745.35);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (90, 251, 38, 1384.57);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (69, 218, 39, 2759.44);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (70, 222, 40, 2365.9);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (97, 293, 41, 1131.74);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (14, 241, 42, 2174.86);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (13, 291, 43, 2440.35);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (49, 188, 44, 1375.58);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (37, 171, 45, 1678.82);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (23, 157, 46, 2515.49);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (13, 117, 47, 1957.7);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (94, 267, 48, 1409.83);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (42, 180, 49, 2193.96);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (59, 202, 50, 1832.05);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (16, 276, 51, 1163.21);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (77, 257, 52, 2868.64);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (65, 220, 53, 2452.42);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (46, 125, 54, 2185.02);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (76, 277, 55, 2835.84);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (68, 176, 56, 1167.61);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (2, 123, 57, 2916.8);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (89, 123, 58, 1528.7);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (74, 235, 59, 2889.39);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (60, 145, 60, 2246.76);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (62, 204, 61, 2204.17);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (77, 110, 62, 2409.74);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (64, 287, 63, 2202.29);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (93, 226, 64, 1337.71);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (29, 130, 65, 2045.32);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (15, 277, 66, 1398.63);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (82, 294, 67, 2667.41);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (37, 251, 68, 2315.05);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (31, 217, 69, 1780.86);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (27, 273, 70, 2137.49);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (42, 144, 71, 2766.16);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (59, 236, 72, 2265.07);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (72, 178, 73, 1579.3);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (6, 154, 74, 2805.04);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (15, 262, 75, 2467.49);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (48, 187, 76, 1683.76);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (75, 292, 77, 2589.07);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (81, 231, 78, 1370.91);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (55, 290, 79, 1907.93);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (78, 268, 80, 2395.29);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (61, 275, 81, 2000.88);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (54, 185, 82, 2605.89);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (2, 181, 83, 1383.77);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (13, 213, 84, 1305.84);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (57, 122, 85, 1343.45);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (95, 211, 86, 2128.21);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (16, 294, 87, 2787.43);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (17, 206, 88, 2011.18);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (53, 251, 89, 2788.92);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (71, 156, 90, 1423.54);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (15, 159, 91, 1053.98);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (86, 287, 92, 2491.05);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (56, 208, 93, 2286.69);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (84, 137, 94, 1939.59);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (37, 276, 95, 2928.19);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (95, 188, 96, 2410.51);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (25, 270, 97, 2144.39);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (98, 214, 98, 1617.1);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (63, 181, 99, 2663.26);
insert into OrderItem (OrderId, ProductId, Quantity, UnitPrice) values (20, 108, 100, 2077.08);
/*order*/
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'CTI Industries Corporation', 23321.03);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Western Asset High Income Opportunity Fund, Inc.', 7769.67);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'MainSource Financial Group, Inc.', 23377.64);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'RPM International Inc.', 17437.92);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'CONMED Corporation', 9158.46);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, '58.com Inc.', 23377.63);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'R.R. Donnelley & Sons Company', 12647.64);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Darling Ingredients Inc.', 2434.97);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Horizons DAX Germany ETF', 22932.67);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Boston Properties, Inc.', 14631.74);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'WNS (Holdings) Limited', 10673.47);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Nexeo Solutions, Inc.', 6746.67);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'ClearBridge Energy MLP Opportunity Fund Inc.', 12089.23);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Weis Markets, Inc.', 21531.95);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Vuzix Corporation', 1655.15);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Gazit-Globe Ltd.', 7882.0);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Forum Merger Corporation', 6283.22);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Forest City Realty Trust, Inc.', 19388.76);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Huntington Bancshares Incorporated', 3577.71);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Babcock', 27258.38);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Range Resources Corporation', 4345.49);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Cirrus Logic, Inc.', 23997.58);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Granite Real Estate Inc.', 25362.05);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'American Railcar Industries, Inc.', 24082.53);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Nuveen Tax-Advantaged Dividend Growth Fund', 27181.18);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Automatic Data Processing, Inc.', 5251.28);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Visteon Corporation', 12730.82);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Forum Merger Corporation', 26097.55);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Kinder Morgan, Inc.', 5742.41);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'First Trust Large Cap Value AlphaDEX Fund', 11997.26);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, '500.com Limited', 29224.12);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Community Health Systems, Inc.', 26527.37);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Banco De Chile', 1532.39);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Ericsson', 10546.43);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Attunity Ltd.', 1451.35);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Transportadora De Gas Sa Ord B', 5994.86);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Athersys, Inc.', 26027.18);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'First Trust Total US Market AlphaDEX ETF', 1577.99);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Cliffs Natural Resources Inc.', 21407.54);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Public Storage', 3997.4);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Rand Capital Corporation', 19696.79);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Public Storage', 2027.38);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Immuron Limited', 12466.05);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'The Middleby Corporation', 12514.93);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'MYOS RENS Technology Inc.', 23982.14);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'GDS Holdings Limited', 17555.56);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Applied Optoelectronics, Inc.', 1592.4);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Cempra, Inc.', 22108.68);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'S&W Seed Company', 27916.05);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'G. Willi-Food International,  Ltd.', 22809.85);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Terreno Realty Corporation', 1351.98);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'IHS Markit Ltd.', 19937.63);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Pure Cycle Corporation', 25028.89);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Panera Bread Company', 27885.45);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'BGC Partners, Inc.', 26483.77);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Brunswick Corporation', 24327.51);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Umpqua Holdings Corporation', 13886.93);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'WNS (Holdings) Limited', 17618.66);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Public Storage', 2197.84);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Black Hills Corporation', 8183.01);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'First Trust Strategic High Income Fund II', 7998.82);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'XTL Biopharmaceuticals Ltd.', 2311.82);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Nuveen Arizona Quality Municipal Income Fund', 20710.48);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Attunity Ltd.', 16577.97);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Five9, Inc.', 20553.86);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Bellerophon Therapeutics, Inc.', 15934.15);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'MainSource Financial Group, Inc.', 27611.13);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Netshoes (Cayman) Limited', 4940.69);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Medley Capital Corporation', 28302.18);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Bancorp 34, Inc.', 12284.29);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Scorpio Bulkers Inc.', 4328.09);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Abraxas Petroleum Corporation', 6858.55);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'First Trust NASDAQ-100- Technology Index Fund', 3571.83);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Summit Therapeutics plc', 20178.33);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'TOP Ships Inc.', 24012.13);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'China Southern Airlines Company Limited', 9409.03);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'MEDIFAST INC', 14523.79);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Marchex, Inc.', 15936.1);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Frequency Electronics, Inc.', 20707.54);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Crown Crafts, Inc.', 27167.25);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'PowerShares KBW Regional Banking Portfolio', 4450.27);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'WisdomTree Japan Hedged SmallCap Equity Fund', 23217.71);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Molson Coors Brewing  Company', 12149.6);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Moleculin Biotech, Inc.', 5028.83);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Insmed, Inc.', 7935.79);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'First Trust High Income ETF', 25677.99);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Magyar Bancorp, Inc.', 5342.3);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'Enable Midstream Partners, LP', 21309.96);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Biolase, Inc.', 16392.95);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Netshoes (Cayman) Limited', 18382.13);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'TravelCenters of America LLC', 11035.08);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Himax Technologies, Inc.', 22993.79);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'Cencosud S.A.', 7260.26);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Gulf Resources, Inc.', 15915.47);
insert into [Order] (CustomerId, [Status], TotalAmount) values (3, 'iStar Financial Inc.', 22602.68);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'BancorpSouth, Inc.', 24267.34);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Aehr Test Systems', 29162.78);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'First Commonwealth Financial Corporation', 22017.14);
insert into [Order] (CustomerId, [Status], TotalAmount) values (1, 'Ritter Pharmaceuticals, Inc.', 14055.71);
insert into [Order] (CustomerId, [Status], TotalAmount) values (2, 'AMN Healthcare Services Inc', 17043.01);
/*payment*/
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (61, 1262.96, 'SEK', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (84, 1580.32, 'CAD', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (74, 2582.61, 'CNY', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (31, 2325.39, 'IDR', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (5, 2419.52, 'IDR', 'LA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (9, 1616.17, 'MNT', 'CO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (15, 2855.15, 'UAH', 'FL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (75, 2163.32, 'AFN', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (31, 2969.76, 'PHP', 'MT');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (96, 1624.42, 'RUB', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (35, 1153.45, 'MVR', 'CO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (17, 2032.87, 'VEF', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (42, 1786.31, 'GTQ', 'MS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (97, 1227.34, 'THB', 'KY');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (47, 2103.33, 'CNY', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (3, 2113.77, 'ARS', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (100, 2273.8, 'PLN', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (49, 1030.0, 'DJF', 'WV');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (14, 1757.8, 'EUR', 'MI');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (51, 1112.09, 'IDR', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (94, 1479.99, 'IDR', 'TN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (45, 1807.36, 'EUR', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (76, 2494.45, 'MXN', 'DE');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (92, 2894.08, 'ZAR', 'MO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (47, 1564.22, 'RUB', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (42, 1143.56, 'BRL', 'MS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (69, 2169.58, 'CLP', 'NE');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (62, 2376.79, 'CNY', 'NY');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (77, 2591.95, 'EUR', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (68, 1563.73, 'EUR', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (20, 2131.79, 'EGP', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (59, 1249.14, 'USD', 'PA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (53, 2959.98, 'AFN', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (30, 1647.37, 'PLN', 'MS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (9, 2815.29, 'EUR', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (6, 1168.58, 'CNY', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (55, 1509.02, 'CNY', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (93, 2523.96, 'SYP', 'KS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (97, 2824.16, 'EUR', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (55, 2155.94, 'EUR', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (35, 1365.6, 'COP', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (32, 2006.62, 'BRL', 'AL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (17, 1090.09, 'GTQ', 'IN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (62, 1354.06, 'PHP', 'IA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (69, 1943.38, 'CNY', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (51, 1634.15, 'AMD', 'PA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (10, 1542.52, 'EUR', 'FL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (33, 2072.01, 'CNY', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (40, 2691.85, 'PHP', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (1, 1812.29, 'COP', 'CT');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (84, 2866.89, 'PLN', 'AR');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (86, 1289.13, 'LKR', 'NY');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (78, 1461.85, 'CNY', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (80, 1901.26, 'GTQ', 'NE');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (96, 1150.91, 'CNY', 'AK');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (98, 1241.96, 'CNY', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (24, 1576.11, 'EUR', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (98, 2408.37, 'BRL', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (55, 1552.67, 'HRK', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (28, 2044.58, 'CNY', 'MO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (28, 2331.33, 'ZAR', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (18, 2703.1, 'BRL', 'IA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (32, 2453.54, 'PLN', 'IA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (15, 1562.2, 'CNY', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (96, 2081.81, 'JPY', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (52, 1470.78, 'NIO', 'PA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (59, 1727.49, 'SEK', 'NY');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (64, 1333.59, 'RUB', 'IN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (67, 1106.2, 'RUB', 'NJ');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (98, 2690.03, 'RSD', 'CO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (24, 1995.53, 'SEK', 'OK');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (8, 2719.42, 'IDR', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (87, 1947.62, 'ETB', 'TX');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (83, 1120.65, 'CNY', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (67, 2420.6, 'AZN', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (100, 1926.27, 'EUR', 'NC');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (30, 2105.94, 'GEL', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (99, 2043.39, 'IDR', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (27, 2214.55, 'IDR', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (66, 1724.53, 'RUB', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (61, 1093.82, 'UAH', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (97, 1027.55, 'RUB', 'LA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (7, 2182.32, 'TJS', 'LA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (28, 2455.02, 'IDR', 'NE');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (47, 2420.55, 'EUR', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (64, 1240.85, 'IDR', 'NJ');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (57, 2139.88, 'IDR', 'VA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (65, 2937.38, 'BRL', 'MO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (74, 2559.55, 'PLN', 'KS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (45, 2157.53, 'CNY', 'OH');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (95, 1506.94, 'PHP', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (89, 2145.06, 'EUR', 'MS');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (13, 2878.78, 'CNY', 'AL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (30, 2746.1, 'IDR', 'GA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (30, 1424.31, 'CNY', 'CA');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (11, 1952.85, 'IDR', 'MN');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (81, 1240.76, 'MAD', 'MO');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (52, 1832.13, 'IDR', 'IL');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (14, 1430.31, 'VND', 'NY');
insert into Payment (OrderId, Amount, PaymentMethod, PaymentStatus) values (98, 1821.25, 'EUR', 'SD');
/* shipment*/
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (82, 'Suite 92', '2024-12-29 14:49:03', 'malesuada in imperdiet et');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (47, 'Room 1994', '2024-08-03 09:01:28', 'porta volutpat erat quisque');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (92, '12th Floor', '2025-04-17 22:32:21', 'volutpat quam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (73, 'Suite 21', '2024-08-24 23:06:14', 'venenatis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (40, '6th Floor', '2024-08-02 05:25:38', 'non pretium quis lectus suspendisse');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (22, '18th Floor', '2025-01-21 21:16:15', 'amet eleifend pede libero quis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (27, '4th Floor', '2025-06-04 10:21:26', 'quis libero nullam sit amet');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (36, 'Suite 68', '2025-06-17 03:47:13', 'nisl nunc nisl duis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (38, '17th Floor', '2025-06-26 14:05:23', 'semper');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (69, 'PO Box 35721', '2025-04-06 18:30:41', 'augue');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (97, 'Room 305', '2024-09-07 04:00:23', 'ut');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (11, '11th Floor', '2024-11-06 12:41:35', 'venenatis lacinia');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (69, 'PO Box 46722', '2024-08-09 11:44:25', 'lectus pellentesque eget');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (94, 'Room 815', '2024-11-26 08:38:00', 'libero rutrum ac lobortis vel');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (79, 'PO Box 93603', '2024-08-27 22:42:27', 'in congue etiam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (61, 'Apt 425', '2024-12-04 07:57:29', 'vitae ipsum aliquam non mauris');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (83, 'Suite 94', '2024-08-10 12:44:58', 'bibendum imperdiet nullam orci');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (38, 'Suite 67', '2025-03-31 09:46:26', 'congue etiam justo etiam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (8, 'Apt 287', '2024-08-21 21:11:02', 'massa volutpat convallis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (60, '7th Floor', '2024-09-08 03:25:53', 'sodales');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, 'Apt 307', '2025-01-30 05:24:03', 'lectus aliquam sit');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (47, 'Room 645', '2024-10-03 16:28:31', 'consequat nulla nisl nunc nisl');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (38, 'PO Box 15472', '2025-02-20 22:43:45', 'odio justo sollicitudin ut');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (9, 'Suite 37', '2024-08-05 10:45:10', 'orci nullam molestie nibh');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (23, 'Suite 56', '2025-03-28 06:00:59', 'erat id mauris vulputate elementum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (40, 'Apt 1051', '2024-11-25 17:16:43', 'ante ipsum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, '1st Floor', '2025-03-07 13:18:32', 'vestibulum velit');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, 'PO Box 64469', '2025-01-06 02:01:41', 'consequat nulla');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (81, '10th Floor', '2025-04-01 10:16:04', 'lobortis est phasellus sit amet');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (38, 'PO Box 4021', '2024-08-14 19:54:35', 'massa');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (2, 'Apt 1008', '2025-02-03 10:50:46', 'quam a odio');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (56, 'Room 1335', '2024-08-30 17:14:48', 'volutpat in');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (55, 'Suite 82', '2024-10-22 06:28:50', 'fringilla rhoncus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (1, 'Apt 1314', '2025-02-07 01:17:24', 'libero ut massa volutpat');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (47, 'Apt 39', '2024-11-02 19:00:07', 'in sagittis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (54, '11th Floor', '2024-11-30 16:18:07', 'elementum ligula');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (99, 'Suite 17', '2025-02-01 13:46:38', 'nascetur ridiculus mus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, 'PO Box 52199', '2025-04-08 13:08:53', 'nunc purus phasellus in');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (27, 'Apt 1464', '2025-06-13 14:07:07', 'sapien');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (61, '12th Floor', '2024-09-23 21:09:36', 'rutrum nulla tellus in sagittis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (65, 'Apt 1640', '2024-07-25 01:12:29', 'proin interdum mauris non ligula');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (68, 'Suite 11', '2025-06-26 07:25:54', 'vulputate vitae nisl aenean lectus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (38, 'Room 1319', '2025-04-23 17:52:04', 'mi');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (39, 'Apt 1220', '2024-12-02 05:19:50', 'nullam molestie nibh in lectus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (67, 'Suite 19', '2025-06-18 02:22:41', 'libero convallis eget eleifend luctus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (98, 'Suite 19', '2024-08-20 10:05:49', 'metus aenean fermentum donec ut');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, '20th Floor', '2025-03-30 14:03:09', 'ac');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (60, 'PO Box 22226', '2024-08-07 08:16:39', 'nullam orci pede venenatis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (22, 'Room 352', '2025-02-02 04:57:11', 'eu massa donec dapibus duis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (49, 'Apt 1631', '2025-05-30 16:54:07', 'vulputate');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (16, 'Apt 1752', '2024-12-14 07:44:36', 'ut ultrices');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (52, 'Room 192', '2025-05-14 13:53:28', 'parturient montes nascetur ridiculus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (86, 'PO Box 51271', '2025-03-17 16:46:46', 'mauris sit amet eros');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (42, '17th Floor', '2024-09-28 19:58:09', 'ut massa');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (81, 'Room 29', '2025-04-17 11:40:40', 'nunc commodo placerat praesent blandit');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (1, 'Suite 3', '2024-10-15 00:44:13', 'libero');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (65, 'Apt 251', '2025-01-22 16:56:39', 'elit proin interdum mauris');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (32, 'Suite 87', '2025-04-20 04:36:11', 'porta volutpat erat');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (31, 'Suite 33', '2025-02-20 10:11:38', 'mattis nibh ligula nec sem');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (61, 'Apt 690', '2024-09-14 12:54:42', 'malesuada');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (17, 'Apt 1252', '2024-08-29 21:25:57', 'primis in faucibus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (65, 'Room 804', '2025-01-22 14:32:39', 'condimentum neque sapien');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (68, 'Apt 1329', '2025-03-22 16:43:51', 'hac habitasse platea dictumst');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (57, 'Suite 100', '2025-01-23 23:43:02', 'eu magna vulputate luctus cum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (20, 'Room 1288', '2024-09-07 07:21:05', 'rutrum ac lobortis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (18, 'Apt 355', '2024-12-18 16:01:31', 'habitasse platea');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (89, 'Room 445', '2025-01-10 10:14:14', 'integer tincidunt ante vel ipsum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (22, 'Apt 1317', '2025-05-08 10:46:58', 'diam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (47, 'Apt 1152', '2025-06-10 20:24:56', 'nisi volutpat');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (45, 'Suite 41', '2025-02-08 19:05:57', 'habitasse platea dictumst morbi');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (36, 'Room 191', '2024-07-10 17:59:20', 'purus phasellus in');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (90, 'Suite 16', '2025-05-12 17:40:48', 'tellus in sagittis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (36, 'Room 1690', '2024-12-29 20:43:49', 'eget elit');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (70, 'PO Box 25975', '2025-05-23 00:33:40', 'nisl');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (76, 'Suite 12', '2025-04-25 22:49:55', 'tristique est et');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (65, 'Room 339', '2024-09-09 12:23:17', 'sit amet justo morbi ut');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (87, '6th Floor', '2025-02-05 13:21:05', 'et ultrices posuere');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (45, 'Apt 1701', '2024-08-12 21:36:52', 'primis in faucibus orci luctus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (12, '9th Floor', '2025-01-17 14:07:43', 'pede lobortis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (84, 'Room 1665', '2025-06-03 10:43:33', 'venenatis non sodales sed tincidunt');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (62, 'Suite 87', '2024-08-01 20:28:08', 'suspendisse');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (84, '9th Floor', '2024-11-05 04:25:15', 'dictumst');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (37, 'Suite 83', '2025-05-17 10:40:40', 'lacinia');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (46, 'Apt 1045', '2024-10-16 09:42:48', 'mattis pulvinar nulla');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (93, 'PO Box 64223', '2024-10-15 20:41:20', 'aliquam sit amet diam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (78, '16th Floor', '2025-03-18 21:14:45', 'suspendisse');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (41, 'Room 1316', '2024-10-18 13:34:35', 'aliquam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (44, 'PO Box 20729', '2025-06-16 05:00:03', 'aliquet massa id lobortis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (54, 'Suite 87', '2024-08-01 18:29:31', 'cras non');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (21, 'Apt 1557', '2024-11-02 16:22:30', 'rutrum nulla tellus in');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (68, 'PO Box 79894', '2024-08-26 00:18:26', 'nisi volutpat eleifend');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (86, 'Room 266', '2024-10-15 09:21:48', 'dis parturient montes nascetur ridiculus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (73, 'Suite 98', '2025-04-02 11:49:40', 'metus sapien ut nunc vestibulum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (30, 'Room 77', '2024-10-16 23:20:31', 'tincidunt lacus at velit');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (51, 'Apt 1349', '2024-09-06 16:26:42', 'maecenas ut');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (95, 'Suite 74', '2025-05-16 08:38:13', 'faucibus orci luctus');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (23, 'Suite 42', '2025-02-17 10:31:59', 'consectetuer eget rutrum');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (91, 'Room 793', '2024-10-20 01:02:51', 'nunc proin at turpis');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (11, '18th Floor', '2025-04-22 02:22:29', 'duis aliquam');
insert into Shipment (OrderId, Address, ShippedDate, DeliveryStatus) values (91, 'Apt 210', '2025-04-04 00:34:55', 'vitae quam suspendisse');

create PROCEDURE Show_Data
@name nvarchar(128)
as
begin
declare @tablename nvarchar(Max)
Set @tablename = 'select * from '+ @name
exec sp_executesql @tablename
end;
go

exec Show_Data @name='productAndCategory'

Create procedure OuterJoin
@tb1Name nvarchar(120),
@tb2Name nvarchar(120)
as
begin
declare @sql nvarchar(Max);
set @sql='select * from '+ QUOTENAME(@tb1Name) +' t1 
Full outer join '+QUOTENAME(@tb2Name)+' t2 
ON t1.Id= t2.ProductId';
exec sp_executesql @sql
end;
go

exec OuterJoin @tb1Name='products',@tb2Name='productAndCategory'

select Count(p.Id) as productcount
from products as p
inner join productAndCategory as pc on pc.ProductId= p.Id
inner join categories as c on c.Id=pc.CategoryId
where c.CategoryName='Samsung';

create procedure innerJoin
@categoryname nvarchar(Max)
as
begin
declare @sql nvarchar(Max);
set @sql='select
p.ProductName,
c.CategoryName,
pc.ProductId
from 
products as p
inner join productAndCategory as pc on pc.ProductId= p.Id
inner join categories as c on c.Id=pc.CategoryId
where c.CategoryName= @catname';
exec sp_executesql @sql,N'@catname Nvarchar(Max)',@catname=@categoryname;
end;
go


exec innerJoin @categoryname='Samsung'

select SUM(p.rows) as totalerow
from sys.tables as t
join sys.partitions p on t.object_id=p.object_id
where p.index_id IN (0,1);

SELECT name FROM sys.databases WHERE name = 'heaven';

use master
go

alter Database [heaven]
set offline with rollback immediate

alter Database [heaven] set online

ALTER Database [heaven] MODIFY NAME = Novexa;